/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xikang.channel.common.rpc.thrift.message;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Region implements org.apache.thrift.TEnum {
  CN(0),
  US(1);

  private final int value;

  private Region(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Region findByValue(int value) { 
    switch (value) {
      case 0:
        return CN;
      case 1:
        return US;
      default:
        return null;
    }
  }
}
