/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xikang.channel.base.rpc.thrift.app;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AppService {

  public interface Iface {

    public VersionInfo validateVersion(com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs) throws com.xikang.channel.common.rpc.thrift.message.AuthException, com.xikang.channel.common.rpc.thrift.message.BizException, org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void validateVersion(com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.validateVersion_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public VersionInfo validateVersion(com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs) throws com.xikang.channel.common.rpc.thrift.message.AuthException, com.xikang.channel.common.rpc.thrift.message.BizException, org.apache.thrift.TException
    {
      send_validateVersion(commArgs);
      return recv_validateVersion();
    }

    public void send_validateVersion(com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs) throws org.apache.thrift.TException
    {
      validateVersion_args args = new validateVersion_args();
      args.setCommArgs(commArgs);
      sendBase("validateVersion", args);
    }

    public VersionInfo recv_validateVersion() throws com.xikang.channel.common.rpc.thrift.message.AuthException, com.xikang.channel.common.rpc.thrift.message.BizException, org.apache.thrift.TException
    {
      validateVersion_result result = new validateVersion_result();
      receiveBase(result, "validateVersion");
      if (result.isSetSuccess()) {
        return result.success;
      }
      if (result.ae != null) {
        throw result.ae;
      }
      if (result.be != null) {
        throw result.be;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "validateVersion failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void validateVersion(com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs, org.apache.thrift.async.AsyncMethodCallback<validateVersion_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      validateVersion_call method_call = new validateVersion_call(commArgs, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class validateVersion_call extends org.apache.thrift.async.TAsyncMethodCall {
      private com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs;
      public validateVersion_call(com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs, org.apache.thrift.async.AsyncMethodCallback<validateVersion_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.commArgs = commArgs;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("validateVersion", org.apache.thrift.protocol.TMessageType.CALL, 0));
        validateVersion_args args = new validateVersion_args();
        args.setCommArgs(commArgs);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public VersionInfo getResult() throws com.xikang.channel.common.rpc.thrift.message.AuthException, com.xikang.channel.common.rpc.thrift.message.BizException, org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_validateVersion();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("validateVersion", new validateVersion());
      return processMap;
    }

    private static class validateVersion<I extends Iface> extends org.apache.thrift.ProcessFunction<I, validateVersion_args> {
      public validateVersion() {
        super("validateVersion");
      }

      protected validateVersion_args getEmptyArgsInstance() {
        return new validateVersion_args();
      }

      protected validateVersion_result getResult(I iface, validateVersion_args args) throws org.apache.thrift.TException {
        validateVersion_result result = new validateVersion_result();
        try {
          result.success = iface.validateVersion(args.commArgs);
        } catch (com.xikang.channel.common.rpc.thrift.message.AuthException ae) {
          result.ae = ae;
        } catch (com.xikang.channel.common.rpc.thrift.message.BizException be) {
          result.be = be;
        }
        return result;
      }
    }

  }

  public static class validateVersion_args implements org.apache.thrift.TBase<validateVersion_args, validateVersion_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("validateVersion_args");

    private static final org.apache.thrift.protocol.TField COMM_ARGS_FIELD_DESC = new org.apache.thrift.protocol.TField("commArgs", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new validateVersion_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new validateVersion_argsTupleSchemeFactory());
    }

    public com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      COMM_ARGS((short)1, "commArgs");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // COMM_ARGS
            return COMM_ARGS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.COMM_ARGS, new org.apache.thrift.meta_data.FieldMetaData("commArgs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.xikang.channel.common.rpc.thrift.message.CommArgs.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(validateVersion_args.class, metaDataMap);
    }

    public validateVersion_args() {
    }

    public validateVersion_args(
      com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs)
    {
      this();
      this.commArgs = commArgs;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public validateVersion_args(validateVersion_args other) {
      if (other.isSetCommArgs()) {
        this.commArgs = new com.xikang.channel.common.rpc.thrift.message.CommArgs(other.commArgs);
      }
    }

    public validateVersion_args deepCopy() {
      return new validateVersion_args(this);
    }

    @Override
    public void clear() {
      this.commArgs = null;
    }

    public com.xikang.channel.common.rpc.thrift.message.CommArgs getCommArgs() {
      return this.commArgs;
    }

    public validateVersion_args setCommArgs(com.xikang.channel.common.rpc.thrift.message.CommArgs commArgs) {
      this.commArgs = commArgs;
      return this;
    }

    public void unsetCommArgs() {
      this.commArgs = null;
    }

    /** Returns true if field commArgs is set (has been assigned a value) and false otherwise */
    public boolean isSetCommArgs() {
      return this.commArgs != null;
    }

    public void setCommArgsIsSet(boolean value) {
      if (!value) {
        this.commArgs = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case COMM_ARGS:
        if (value == null) {
          unsetCommArgs();
        } else {
          setCommArgs((com.xikang.channel.common.rpc.thrift.message.CommArgs)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case COMM_ARGS:
        return getCommArgs();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case COMM_ARGS:
        return isSetCommArgs();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof validateVersion_args)
        return this.equals((validateVersion_args)that);
      return false;
    }

    public boolean equals(validateVersion_args that) {
      if (that == null)
        return false;

      boolean this_present_commArgs = true && this.isSetCommArgs();
      boolean that_present_commArgs = true && that.isSetCommArgs();
      if (this_present_commArgs || that_present_commArgs) {
        if (!(this_present_commArgs && that_present_commArgs))
          return false;
        if (!this.commArgs.equals(that.commArgs))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(validateVersion_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      validateVersion_args typedOther = (validateVersion_args)other;

      lastComparison = Boolean.valueOf(isSetCommArgs()).compareTo(typedOther.isSetCommArgs());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetCommArgs()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commArgs, typedOther.commArgs);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("validateVersion_args(");
      boolean first = true;

      sb.append("commArgs:");
      if (this.commArgs == null) {
        sb.append("null");
      } else {
        sb.append(this.commArgs);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class validateVersion_argsStandardSchemeFactory implements SchemeFactory {
      public validateVersion_argsStandardScheme getScheme() {
        return new validateVersion_argsStandardScheme();
      }
    }

    private static class validateVersion_argsStandardScheme extends StandardScheme<validateVersion_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, validateVersion_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // COMM_ARGS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.commArgs = new com.xikang.channel.common.rpc.thrift.message.CommArgs();
                struct.commArgs.read(iprot);
                struct.setCommArgsIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, validateVersion_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.commArgs != null) {
          oprot.writeFieldBegin(COMM_ARGS_FIELD_DESC);
          struct.commArgs.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class validateVersion_argsTupleSchemeFactory implements SchemeFactory {
      public validateVersion_argsTupleScheme getScheme() {
        return new validateVersion_argsTupleScheme();
      }
    }

    private static class validateVersion_argsTupleScheme extends TupleScheme<validateVersion_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, validateVersion_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetCommArgs()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetCommArgs()) {
          struct.commArgs.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, validateVersion_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.commArgs = new com.xikang.channel.common.rpc.thrift.message.CommArgs();
          struct.commArgs.read(iprot);
          struct.setCommArgsIsSet(true);
        }
      }
    }

  }

  public static class validateVersion_result implements org.apache.thrift.TBase<validateVersion_result, validateVersion_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("validateVersion_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);
    private static final org.apache.thrift.protocol.TField AE_FIELD_DESC = new org.apache.thrift.protocol.TField("ae", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField BE_FIELD_DESC = new org.apache.thrift.protocol.TField("be", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new validateVersion_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new validateVersion_resultTupleSchemeFactory());
    }

    public VersionInfo success; // required
    public com.xikang.channel.common.rpc.thrift.message.AuthException ae; // required
    public com.xikang.channel.common.rpc.thrift.message.BizException be; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success"),
      AE((short)1, "ae"),
      BE((short)2, "be");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          case 1: // AE
            return AE;
          case 2: // BE
            return BE;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, VersionInfo.class)));
      tmpMap.put(_Fields.AE, new org.apache.thrift.meta_data.FieldMetaData("ae", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
      tmpMap.put(_Fields.BE, new org.apache.thrift.meta_data.FieldMetaData("be", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(validateVersion_result.class, metaDataMap);
    }

    public validateVersion_result() {
    }

    public validateVersion_result(
      VersionInfo success,
      com.xikang.channel.common.rpc.thrift.message.AuthException ae,
      com.xikang.channel.common.rpc.thrift.message.BizException be)
    {
      this();
      this.success = success;
      this.ae = ae;
      this.be = be;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public validateVersion_result(validateVersion_result other) {
      if (other.isSetSuccess()) {
        this.success = new VersionInfo(other.success);
      }
      if (other.isSetAe()) {
        this.ae = new com.xikang.channel.common.rpc.thrift.message.AuthException(other.ae);
      }
      if (other.isSetBe()) {
        this.be = new com.xikang.channel.common.rpc.thrift.message.BizException(other.be);
      }
    }

    public validateVersion_result deepCopy() {
      return new validateVersion_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
      this.ae = null;
      this.be = null;
    }

    public VersionInfo getSuccess() {
      return this.success;
    }

    public validateVersion_result setSuccess(VersionInfo success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public com.xikang.channel.common.rpc.thrift.message.AuthException getAe() {
      return this.ae;
    }

    public validateVersion_result setAe(com.xikang.channel.common.rpc.thrift.message.AuthException ae) {
      this.ae = ae;
      return this;
    }

    public void unsetAe() {
      this.ae = null;
    }

    /** Returns true if field ae is set (has been assigned a value) and false otherwise */
    public boolean isSetAe() {
      return this.ae != null;
    }

    public void setAeIsSet(boolean value) {
      if (!value) {
        this.ae = null;
      }
    }

    public com.xikang.channel.common.rpc.thrift.message.BizException getBe() {
      return this.be;
    }

    public validateVersion_result setBe(com.xikang.channel.common.rpc.thrift.message.BizException be) {
      this.be = be;
      return this;
    }

    public void unsetBe() {
      this.be = null;
    }

    /** Returns true if field be is set (has been assigned a value) and false otherwise */
    public boolean isSetBe() {
      return this.be != null;
    }

    public void setBeIsSet(boolean value) {
      if (!value) {
        this.be = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((VersionInfo)value);
        }
        break;

      case AE:
        if (value == null) {
          unsetAe();
        } else {
          setAe((com.xikang.channel.common.rpc.thrift.message.AuthException)value);
        }
        break;

      case BE:
        if (value == null) {
          unsetBe();
        } else {
          setBe((com.xikang.channel.common.rpc.thrift.message.BizException)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      case AE:
        return getAe();

      case BE:
        return getBe();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      case AE:
        return isSetAe();
      case BE:
        return isSetBe();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof validateVersion_result)
        return this.equals((validateVersion_result)that);
      return false;
    }

    public boolean equals(validateVersion_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_ae = true && this.isSetAe();
      boolean that_present_ae = true && that.isSetAe();
      if (this_present_ae || that_present_ae) {
        if (!(this_present_ae && that_present_ae))
          return false;
        if (!this.ae.equals(that.ae))
          return false;
      }

      boolean this_present_be = true && this.isSetBe();
      boolean that_present_be = true && that.isSetBe();
      if (this_present_be || that_present_be) {
        if (!(this_present_be && that_present_be))
          return false;
        if (!this.be.equals(that.be))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(validateVersion_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      validateVersion_result typedOther = (validateVersion_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAe()).compareTo(typedOther.isSetAe());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAe()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ae, typedOther.ae);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetBe()).compareTo(typedOther.isSetBe());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetBe()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.be, typedOther.be);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("validateVersion_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("ae:");
      if (this.ae == null) {
        sb.append("null");
      } else {
        sb.append(this.ae);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("be:");
      if (this.be == null) {
        sb.append("null");
      } else {
        sb.append(this.be);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class validateVersion_resultStandardSchemeFactory implements SchemeFactory {
      public validateVersion_resultStandardScheme getScheme() {
        return new validateVersion_resultStandardScheme();
      }
    }

    private static class validateVersion_resultStandardScheme extends StandardScheme<validateVersion_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, validateVersion_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new VersionInfo();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 1: // AE
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.ae = new com.xikang.channel.common.rpc.thrift.message.AuthException();
                struct.ae.read(iprot);
                struct.setAeIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // BE
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.be = new com.xikang.channel.common.rpc.thrift.message.BizException();
                struct.be.read(iprot);
                struct.setBeIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, validateVersion_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.ae != null) {
          oprot.writeFieldBegin(AE_FIELD_DESC);
          struct.ae.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.be != null) {
          oprot.writeFieldBegin(BE_FIELD_DESC);
          struct.be.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class validateVersion_resultTupleSchemeFactory implements SchemeFactory {
      public validateVersion_resultTupleScheme getScheme() {
        return new validateVersion_resultTupleScheme();
      }
    }

    private static class validateVersion_resultTupleScheme extends TupleScheme<validateVersion_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, validateVersion_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        if (struct.isSetAe()) {
          optionals.set(1);
        }
        if (struct.isSetBe()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
        if (struct.isSetAe()) {
          struct.ae.write(oprot);
        }
        if (struct.isSetBe()) {
          struct.be.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, validateVersion_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.success = new VersionInfo();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
        if (incoming.get(1)) {
          struct.ae = new com.xikang.channel.common.rpc.thrift.message.AuthException();
          struct.ae.read(iprot);
          struct.setAeIsSet(true);
        }
        if (incoming.get(2)) {
          struct.be = new com.xikang.channel.common.rpc.thrift.message.BizException();
          struct.be.read(iprot);
          struct.setBeIsSet(true);
        }
      }
    }

  }

}
