/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xikang.channel.base.rpc.thrift.app;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum VersionStatus implements org.apache.thrift.TEnum {
  RECOMMENDED(0),
  COMPATIBLE(1),
  INCOMPATIBLE(2);

  private final int value;

  private VersionStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static VersionStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return RECOMMENDED;
      case 1:
        return COMPATIBLE;
      case 2:
        return INCOMPATIBLE;
      default:
        return null;
    }
  }
}
