/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xikang.channel.base.rpc.thrift.auth;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LoginExtInfo implements org.apache.thrift.TBase<LoginExtInfo, LoginExtInfo._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LoginExtInfo");

  private static final org.apache.thrift.protocol.TField APNS_DEVICE_TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("apnsDeviceToken", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new LoginExtInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new LoginExtInfoTupleSchemeFactory());
  }

  public String apnsDeviceToken; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    APNS_DEVICE_TOKEN((short)1, "apnsDeviceToken");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // APNS_DEVICE_TOKEN
          return APNS_DEVICE_TOKEN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.APNS_DEVICE_TOKEN, new org.apache.thrift.meta_data.FieldMetaData("apnsDeviceToken", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LoginExtInfo.class, metaDataMap);
  }

  public LoginExtInfo() {
  }

  public LoginExtInfo(
    String apnsDeviceToken)
  {
    this();
    this.apnsDeviceToken = apnsDeviceToken;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LoginExtInfo(LoginExtInfo other) {
    if (other.isSetApnsDeviceToken()) {
      this.apnsDeviceToken = other.apnsDeviceToken;
    }
  }

  public LoginExtInfo deepCopy() {
    return new LoginExtInfo(this);
  }

  @Override
  public void clear() {
    this.apnsDeviceToken = null;
  }

  public String getApnsDeviceToken() {
    return this.apnsDeviceToken;
  }

  public LoginExtInfo setApnsDeviceToken(String apnsDeviceToken) {
    this.apnsDeviceToken = apnsDeviceToken;
    return this;
  }

  public void unsetApnsDeviceToken() {
    this.apnsDeviceToken = null;
  }

  /** Returns true if field apnsDeviceToken is set (has been assigned a value) and false otherwise */
  public boolean isSetApnsDeviceToken() {
    return this.apnsDeviceToken != null;
  }

  public void setApnsDeviceTokenIsSet(boolean value) {
    if (!value) {
      this.apnsDeviceToken = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case APNS_DEVICE_TOKEN:
      if (value == null) {
        unsetApnsDeviceToken();
      } else {
        setApnsDeviceToken((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case APNS_DEVICE_TOKEN:
      return getApnsDeviceToken();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case APNS_DEVICE_TOKEN:
      return isSetApnsDeviceToken();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof LoginExtInfo)
      return this.equals((LoginExtInfo)that);
    return false;
  }

  public boolean equals(LoginExtInfo that) {
    if (that == null)
      return false;

    boolean this_present_apnsDeviceToken = true && this.isSetApnsDeviceToken();
    boolean that_present_apnsDeviceToken = true && that.isSetApnsDeviceToken();
    if (this_present_apnsDeviceToken || that_present_apnsDeviceToken) {
      if (!(this_present_apnsDeviceToken && that_present_apnsDeviceToken))
        return false;
      if (!this.apnsDeviceToken.equals(that.apnsDeviceToken))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(LoginExtInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    LoginExtInfo typedOther = (LoginExtInfo)other;

    lastComparison = Boolean.valueOf(isSetApnsDeviceToken()).compareTo(typedOther.isSetApnsDeviceToken());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApnsDeviceToken()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.apnsDeviceToken, typedOther.apnsDeviceToken);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LoginExtInfo(");
    boolean first = true;

    sb.append("apnsDeviceToken:");
    if (this.apnsDeviceToken == null) {
      sb.append("null");
    } else {
      sb.append(this.apnsDeviceToken);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LoginExtInfoStandardSchemeFactory implements SchemeFactory {
    public LoginExtInfoStandardScheme getScheme() {
      return new LoginExtInfoStandardScheme();
    }
  }

  private static class LoginExtInfoStandardScheme extends StandardScheme<LoginExtInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LoginExtInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // APNS_DEVICE_TOKEN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.apnsDeviceToken = iprot.readString();
              struct.setApnsDeviceTokenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LoginExtInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.apnsDeviceToken != null) {
        oprot.writeFieldBegin(APNS_DEVICE_TOKEN_FIELD_DESC);
        oprot.writeString(struct.apnsDeviceToken);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LoginExtInfoTupleSchemeFactory implements SchemeFactory {
    public LoginExtInfoTupleScheme getScheme() {
      return new LoginExtInfoTupleScheme();
    }
  }

  private static class LoginExtInfoTupleScheme extends TupleScheme<LoginExtInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LoginExtInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetApnsDeviceToken()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetApnsDeviceToken()) {
        oprot.writeString(struct.apnsDeviceToken);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LoginExtInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.apnsDeviceToken = iprot.readString();
        struct.setApnsDeviceTokenIsSet(true);
      }
    }
  }

}

