/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xikang.channel.base.rpc.thrift.auth;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LoginResultExtInfo implements org.apache.thrift.TBase<LoginResultExtInfo, LoginResultExtInfo._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LoginResultExtInfo");

  private static final org.apache.thrift.protocol.TField CAS_TGT_FIELD_DESC = new org.apache.thrift.protocol.TField("casTgt", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new LoginResultExtInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new LoginResultExtInfoTupleSchemeFactory());
  }

  public String casTgt; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CAS_TGT((short)1, "casTgt");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CAS_TGT
          return CAS_TGT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CAS_TGT, new org.apache.thrift.meta_data.FieldMetaData("casTgt", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LoginResultExtInfo.class, metaDataMap);
  }

  public LoginResultExtInfo() {
  }

  public LoginResultExtInfo(
    String casTgt)
  {
    this();
    this.casTgt = casTgt;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LoginResultExtInfo(LoginResultExtInfo other) {
    if (other.isSetCasTgt()) {
      this.casTgt = other.casTgt;
    }
  }

  public LoginResultExtInfo deepCopy() {
    return new LoginResultExtInfo(this);
  }

  @Override
  public void clear() {
    this.casTgt = null;
  }

  public String getCasTgt() {
    return this.casTgt;
  }

  public LoginResultExtInfo setCasTgt(String casTgt) {
    this.casTgt = casTgt;
    return this;
  }

  public void unsetCasTgt() {
    this.casTgt = null;
  }

  /** Returns true if field casTgt is set (has been assigned a value) and false otherwise */
  public boolean isSetCasTgt() {
    return this.casTgt != null;
  }

  public void setCasTgtIsSet(boolean value) {
    if (!value) {
      this.casTgt = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CAS_TGT:
      if (value == null) {
        unsetCasTgt();
      } else {
        setCasTgt((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CAS_TGT:
      return getCasTgt();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CAS_TGT:
      return isSetCasTgt();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof LoginResultExtInfo)
      return this.equals((LoginResultExtInfo)that);
    return false;
  }

  public boolean equals(LoginResultExtInfo that) {
    if (that == null)
      return false;

    boolean this_present_casTgt = true && this.isSetCasTgt();
    boolean that_present_casTgt = true && that.isSetCasTgt();
    if (this_present_casTgt || that_present_casTgt) {
      if (!(this_present_casTgt && that_present_casTgt))
        return false;
      if (!this.casTgt.equals(that.casTgt))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(LoginResultExtInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    LoginResultExtInfo typedOther = (LoginResultExtInfo)other;

    lastComparison = Boolean.valueOf(isSetCasTgt()).compareTo(typedOther.isSetCasTgt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCasTgt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.casTgt, typedOther.casTgt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LoginResultExtInfo(");
    boolean first = true;

    sb.append("casTgt:");
    if (this.casTgt == null) {
      sb.append("null");
    } else {
      sb.append(this.casTgt);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LoginResultExtInfoStandardSchemeFactory implements SchemeFactory {
    public LoginResultExtInfoStandardScheme getScheme() {
      return new LoginResultExtInfoStandardScheme();
    }
  }

  private static class LoginResultExtInfoStandardScheme extends StandardScheme<LoginResultExtInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LoginResultExtInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CAS_TGT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.casTgt = iprot.readString();
              struct.setCasTgtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LoginResultExtInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.casTgt != null) {
        oprot.writeFieldBegin(CAS_TGT_FIELD_DESC);
        oprot.writeString(struct.casTgt);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LoginResultExtInfoTupleSchemeFactory implements SchemeFactory {
    public LoginResultExtInfoTupleScheme getScheme() {
      return new LoginResultExtInfoTupleScheme();
    }
  }

  private static class LoginResultExtInfoTupleScheme extends TupleScheme<LoginResultExtInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LoginResultExtInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCasTgt()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCasTgt()) {
        oprot.writeString(struct.casTgt);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LoginResultExtInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.casTgt = iprot.readString();
        struct.setCasTgtIsSet(true);
      }
    }
  }

}

