/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xikang.channel.familyexpress.rpc.thrift.express;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AppInitInfo implements org.apache.thrift.TBase<AppInitInfo, AppInitInfo._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AppInitInfo");

  private static final org.apache.thrift.protocol.TField GUIDE_ASST_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("guideAsstId", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AppInitInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AppInitInfoTupleSchemeFactory());
  }

  public String guideAsstId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GUIDE_ASST_ID((short)1, "guideAsstId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GUIDE_ASST_ID
          return GUIDE_ASST_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GUIDE_ASST_ID, new org.apache.thrift.meta_data.FieldMetaData("guideAsstId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AppInitInfo.class, metaDataMap);
  }

  public AppInitInfo() {
  }

  public AppInitInfo(
    String guideAsstId)
  {
    this();
    this.guideAsstId = guideAsstId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AppInitInfo(AppInitInfo other) {
    if (other.isSetGuideAsstId()) {
      this.guideAsstId = other.guideAsstId;
    }
  }

  public AppInitInfo deepCopy() {
    return new AppInitInfo(this);
  }

  @Override
  public void clear() {
    this.guideAsstId = null;
  }

  public String getGuideAsstId() {
    return this.guideAsstId;
  }

  public AppInitInfo setGuideAsstId(String guideAsstId) {
    this.guideAsstId = guideAsstId;
    return this;
  }

  public void unsetGuideAsstId() {
    this.guideAsstId = null;
  }

  /** Returns true if field guideAsstId is set (has been assigned a value) and false otherwise */
  public boolean isSetGuideAsstId() {
    return this.guideAsstId != null;
  }

  public void setGuideAsstIdIsSet(boolean value) {
    if (!value) {
      this.guideAsstId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GUIDE_ASST_ID:
      if (value == null) {
        unsetGuideAsstId();
      } else {
        setGuideAsstId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GUIDE_ASST_ID:
      return getGuideAsstId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GUIDE_ASST_ID:
      return isSetGuideAsstId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AppInitInfo)
      return this.equals((AppInitInfo)that);
    return false;
  }

  public boolean equals(AppInitInfo that) {
    if (that == null)
      return false;

    boolean this_present_guideAsstId = true && this.isSetGuideAsstId();
    boolean that_present_guideAsstId = true && that.isSetGuideAsstId();
    if (this_present_guideAsstId || that_present_guideAsstId) {
      if (!(this_present_guideAsstId && that_present_guideAsstId))
        return false;
      if (!this.guideAsstId.equals(that.guideAsstId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(AppInitInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    AppInitInfo typedOther = (AppInitInfo)other;

    lastComparison = Boolean.valueOf(isSetGuideAsstId()).compareTo(typedOther.isSetGuideAsstId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGuideAsstId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.guideAsstId, typedOther.guideAsstId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AppInitInfo(");
    boolean first = true;

    sb.append("guideAsstId:");
    if (this.guideAsstId == null) {
      sb.append("null");
    } else {
      sb.append(this.guideAsstId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AppInitInfoStandardSchemeFactory implements SchemeFactory {
    public AppInitInfoStandardScheme getScheme() {
      return new AppInitInfoStandardScheme();
    }
  }

  private static class AppInitInfoStandardScheme extends StandardScheme<AppInitInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AppInitInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GUIDE_ASST_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.guideAsstId = iprot.readString();
              struct.setGuideAsstIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AppInitInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.guideAsstId != null) {
        oprot.writeFieldBegin(GUIDE_ASST_ID_FIELD_DESC);
        oprot.writeString(struct.guideAsstId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AppInitInfoTupleSchemeFactory implements SchemeFactory {
    public AppInitInfoTupleScheme getScheme() {
      return new AppInitInfoTupleScheme();
    }
  }

  private static class AppInitInfoTupleScheme extends TupleScheme<AppInitInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AppInitInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetGuideAsstId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetGuideAsstId()) {
        oprot.writeString(struct.guideAsstId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AppInitInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.guideAsstId = iprot.readString();
        struct.setGuideAsstIdIsSet(true);
      }
    }
  }

}

