/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.xikang.channel.familyexpress.rpc.thrift.express;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FEContentType implements org.apache.thrift.TEnum {
  TEXT(1),
  AUDIO(2),
  IMAGE(3);

  private final int value;

  private FEContentType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FEContentType findByValue(int value) { 
    switch (value) {
      case 1:
        return TEXT;
      case 2:
        return AUDIO;
      case 3:
        return IMAGE;
      default:
        return null;
    }
  }
}
